"""empty message

Revision ID: 0211e95e1a86
Revises: 24807ef5da3e
Create Date: 2025-01-15 13:59:18.307421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0211e95e1a86'
down_revision = '24807ef5da3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_url', sa.String(length=128), nullable=True))
        batch_op.drop_column('resutl_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resutl_url', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('result_url')

    # ### end Alembic commands ###
