"""empty message

Revision ID: 0f6b40ead807
Revises: 65c454ed2195
Create Date: 2025-01-21 19:33:29.043627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6b40ead807'
down_revision = '65c454ed2195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_news_types_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_news_types_name'), type_='unique')

    # ### end Alembic commands ###
