"""Initial migration

Revision ID: 1ef9f4588a62
Revises: 
Create Date: 2025-01-16 18:31:56.025358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef9f4588a62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=True))
        batch_op.drop_constraint('uq_top_images_type', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_top_images_title'), ['title'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_top_images_title'), type_='unique')
        batch_op.create_unique_constraint('uq_top_images_type', ['type'])
        batch_op.drop_column('title')

    # ### end Alembic commands ###
