"""empty message

Revision ID: 24807ef5da3e
Revises: 1c7e2b40c936
Create Date: 2025-01-14 17:22:42.344487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24807ef5da3e'
down_revision = '1c7e2b40c936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('water_url', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('resutl_url', sa.String(length=128), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.drop_column('resutl_url')
        batch_op.drop_column('water_url')
        batch_op.drop_column('source_url')

    # ### end Alembic commands ###
