"""empty message

Revision ID: 2d09c6e803bb
Revises: 1ef9f4588a62
Create Date: 2025-01-16 20:25:15.659590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d09c6e803bb'
down_revision = '1ef9f4588a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('coverImage', sa.String(length=64), nullable=True),
    sa.Column('auth', sa.String(length=64), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news')),
    sa.UniqueConstraint('type', name=op.f('uq_news_type'))
    )
    op.create_table('news_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_types'))
    )
    op.drop_table('healths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healths',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('coverImage', sa.VARCHAR(length=64), nullable=True),
    sa.Column('auth', sa.VARCHAR(length=64), nullable=True),
    sa.Column('updateTime', sa.DATETIME(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_healths'),
    sa.UniqueConstraint('type', name='uq_healths_type')
    )
    op.drop_table('news_types')
    op.drop_table('news')
    # ### end Alembic commands ###
