"""empty message

Revision ID: 51fffd461fe0
Revises: d00ea08f4a2a
Create Date: 2025-01-23 19:29:44.868957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fffd461fe0'
down_revision = 'd00ea08f4a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_products_name', ['name'])

    # ### end Alembic commands ###
