"""empty message

Revision ID: 52633be885f9
Revises: 725b812b40ee
Create Date: 2024-11-12 17:31:20.573791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52633be885f9'
down_revision = '725b812b40ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
