"""empty message

Revision ID: 52da3e2fd288
Revises: e7342d23ab28
Create Date: 2024-11-29 14:56:11.698094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52da3e2fd288'
down_revision = 'e7342d23ab28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_product_classify', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'classifys', ['fk_product_classify'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_product_classify')

    # ### end Alembic commands ###
