"""empty message

Revision ID: 722c042d8c14
Revises: 7edc21769cc1
Create Date: 2024-11-29 14:51:44.526360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722c042d8c14'
down_revision = '7edc21769cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classify_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'classifys', ['classify_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('classify_id')

    op.drop_table('classifys')
    # ### end Alembic commands ###
