"""empty message

Revision ID: 87dd6295840c
Revises: 19b5ed6277eb
Create Date: 2024-12-04 18:43:22.502450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87dd6295840c'
down_revision = '19b5ed6277eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_images', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_top_images_type'), ['type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_top_images_type'), type_='unique')

    # ### end Alembic commands ###
