"""empty message

Revision ID: 89bda49b4b10
Revises: 4ec32db1be34
Create Date: 2024-12-08 10:18:29.989022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bda49b4b10'
down_revision = '4ec32db1be34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updateTime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('healths', schema=None) as batch_op:
        batch_op.drop_column('updateTime')

    # ### end Alembic commands ###
