"""empty message

Revision ID: b7efb54cb7c4
Revises: 50d8c44a3abb
Create Date: 2025-01-23 16:12:03.717498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7efb54cb7c4'
down_revision = '50d8c44a3abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('uq_news_type', type_='unique')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), nullable=True))
        batch_op.create_unique_constraint('uq_news_type', ['type'])

    # ### end Alembic commands ###
