"""empty message

Revision ID: d50ae3614244
Revises: 52da3e2fd288
Create Date: 2024-11-29 14:57:31.596516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50ae3614244'
down_revision = '52da3e2fd288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classifys', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_classifys_name'), ['name'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_product_classify', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_products_name'), ['name'])
        batch_op.create_foreign_key(batch_op.f('fk_products_fk_product_classify_classifys'), 'classifys', ['fk_product_classify'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_fk_product_classify_classifys'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_products_name'), type_='unique')
        batch_op.drop_column('fk_product_classify')

    with op.batch_alter_table('classifys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_classifys_name'), type_='unique')

    # ### end Alembic commands ###
