"""empty message

Revision ID: e7342d23ab28
Revises: 722c042d8c14
Create Date: 2024-11-29 14:53:29.426751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7342d23ab28'
down_revision = '722c042d8c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classify_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'classifys', ['classify_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('classify_id')

    # ### end Alembic commands ###
